receivers:
  eventreceiver:
    http:
      endpoint: "0.0.0.0:5520"
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:5510"

processors:
  eventenrichprocessor:
    ipresolveservice_url: "0.0.0.0:5501/api/v1/resolve"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug]
    logs:
      receivers: [eventreceiver]
      processors: [eventenrichprocessor]
      exporters: [debug]

