dist:
  name: custom-otel-collector
  description: Custom collector
  output_path: ./otel
#  otelcol_version: 0.113.0
  version: 0.0.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.113.0

processors:
  - gomod: github.com/kostz/eventenrichprocessor v1.0.0
    name: eventenrichprocessor

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.113.0

replaces:
  - github.com/kostz/eventenrichprocessor => ../eventenrichprocessor
