dist:
  name: custom-otel-collector
  description: Custom collector
  output_path: ./otel
  otelcol_version: 0.110.0
  version: 0.0.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.110.0

processors:
  - gomod: github.com/kostz/eventenrichprocessor v1.0.0
    name: eventenrichprocessor

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.16.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.16.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.110.0

replaces:
  - go.opentelemetry.io/collector => go.opentelemetry.io/collector v0.110.0
  - go.opentelemetry.io/collector/exporter => go.opentelemetry.io/collector/exporter v0.110.0
  - go.opentelemetry.io/collector/component => go.opentelemetry.io/collector/component v0.110.0
  - go.opentelemetry.io/collector/processor => go.opentelemetry.io/collector/processor v0.110.0
  - go.opentelemetry.io/collector/receiver => go.opentelemetry.io/collector/receiver v0.110.0
  - go.opentelemetry.io/collector/consumer => go.opentelemetry.io/collector/consumer v0.110.0
  - go.opentelemetry.io/collector/extension => go.opentelemetry.io/collector/extension v0.110.0
  - github.com/kostz/eventenrichprocessor => ../eventenrichprocessor
